// Autogenerated by genigo(0.1.0)
// Please don't edit this file
// If you want add some helpers/triggers you should open a different file such as posts.helper.go
package models

import (
	"log"
	"time"

	"database/sql"
	"github.com/shopspring/decimal"

	"github.com/genigo/goje"
)

type Post struct {
	UserId      int64           `db:"user_id" json:"user_id"`
	Title       string          `db:"title" json:"title"`
	Slug        string          `db:"slug" json:"slug"`
	Body        sql.NullString  `db:"body" json:"body"`
	Rating      decimal.Decimal `db:"rating" json:"rating"`
	Views       int             `db:"views" json:"views"`
	PublishedAt sql.NullTime    `db:"published_at" json:"published_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
	//Primary Key Auto Increment
	Id int64 `db:"id" json:"id"`

	//relation one to one, Users [user_id -> users.id]
	UserIdUser *User `db:"-" json:"user_id_user"`

	//internal context, db handler
	ctx    *goje.Context `db:"-" json:"-"`
	parent goje.Entity   `db:"-" json:"-"`
}

var BeforeInsertPost func(*goje.Context, *Post) error
var BeforeUpdatePost func(*goje.Context, *Post) error
var BeforeDeletePost func(*goje.Context, *Post) error
var AfterInsertPost func(*goje.Context, *Post)
var AfterUpdatePost func(*goje.Context, *Post)
var AfterDeletePost func(*goje.Context, *Post)

const PostTableName = "posts"
const PostPrimaryKey = "id"

// List of Columns of table
var PostColumns = []string{
	"user_id", "title", "slug", "body", "rating", "views", "published_at", "updated_at", "id",
}

// List of Columns merged with table name
var PostColumnsWithTable = []string{
	"posts.user_id", "posts.title", "posts.slug", "posts.body", "posts.rating", "posts.views", "posts.published_at", "posts.updated_at", "posts.id",
}

// Tablename returns real table name in the database
// a helper method for goje.Entity interface
func (opt Post) GetTableName() string {
	return PostTableName
}

// GetCtx returns current context handler
func (opt Post) GetCtx() *goje.Context {
	return opt.ctx
}

// SetCtx set context handler for current object
func (opt *Post) SetCtx(ctx *goje.Context) {
	opt.ctx = ctx
}

// GetParent returns parent object
func (opt Post) GetParent() *goje.Entity {
	return &opt.parent
}

// Columns returns list of table columns
// a helper method for goje.Entity interface
func (opt Post) GetColumns() []string {
	return PostColumns
}

// Delete multiple Post by queries
// This method dosen't support After,Before Triggers ...
func DeletePostRaw(handler *goje.Context, Queries ...goje.QueryInterface) (rowsAffected int64, err error) {
	return handler.RawDelete("posts", Queries)
}

// Insert multiple Post with INTO
// This method dosen't support After,Before Triggers ...
func BulkInsertPost(handler *goje.Context, entities []Post) (rowsInserted int64, err error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}

	rows := make([]map[string]interface{}, len(entities))

	for i := 0; i < len(entities); i++ {
		rows[i] = make(map[string]interface{})
		rows[i]["user_id"] = entities[i].UserId
		rows[i]["title"] = entities[i].Title
		rows[i]["slug"] = entities[i].Slug
		rows[i]["body"] = entities[i].Body
		rows[i]["rating"] = entities[i].Rating
		rows[i]["views"] = entities[i].Views
		rows[i]["published_at"] = entities[i].PublishedAt
		rows[i]["id"] = entities[i].Id
	}
	return handler.RawBulkInsert("posts", rows)
}

// Update custom columns of Post
// This method dosen't support After,Before Triggers ...
func UpdatePost(handler *goje.Context, Cols map[string]any, Queries ...goje.QueryInterface) (rowsAffected int64, err error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}
	return handler.RawUpdate("posts", Cols, Queries...)
}

// Insert multiple Post with IGNORE
// This method dosen't support After,Before Triggers ...
func BulkInsertIgnorePost(handler *goje.Context, entities []Post) (rowsInserted int64, err error) {
	rows := make([]map[string]interface{}, len(entities))

	for i := 0; i < len(entities); i++ {
		rows[i] = make(map[string]interface{})
		rows[i]["user_id"] = entities[i].UserId
		rows[i]["title"] = entities[i].Title
		rows[i]["slug"] = entities[i].Slug
		rows[i]["body"] = entities[i].Body
		rows[i]["rating"] = entities[i].Rating
		rows[i]["views"] = entities[i].Views
		rows[i]["published_at"] = entities[i].PublishedAt
		rows[i]["id"] = entities[i].Id
	}
	return handler.RawBulkInsertIgnore("posts", rows)
}

// Delete delete an entry
func (opt *Post) Delete(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeDeletePost != nil {
		err := BeforeDeletePost(handler, opt)
		if err != nil {
			return err
		}
	}

	start := time.Now()
	// run query
	_, err := handler.DB.ExecContext(handler.Ctx, `DELETE FROM posts WHERE id=?`, opt.Id)

	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=Post.Delete()\n", elapsed)
	}

	if err != nil {
		return err
	}

	if AfterDeletePost != nil {
		AfterDeletePost(handler, opt)
	}

	return nil

}

// Save update an entry when primary key is set or create an entry when primary key isn't set
func (opt *Post) Save(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if opt.Id == 0 {
		return opt.Insert(handler)
	}

	return opt.Update(handler)

}

// Insert create an entry
func (opt *Post) Insert(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeInsertPost != nil {
		err := BeforeInsertPost(handler, opt)
		if err != nil {
			return err
		}
	}

	if opt.UpdatedAt.IsZero() {
		opt.UpdatedAt = time.Now()
	}

	start := time.Now()

	result, err := handler.DB.ExecContext(handler.Ctx, `INSERT INTO posts(user_id,title,slug,body,rating,views,published_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`, opt.UserId, opt.Title, opt.Slug, opt.Body, opt.Rating, opt.Views, opt.PublishedAt, opt.UpdatedAt)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=*Post.Insert()\n", elapsed)
	}

	if err != nil {
		return err
	}

	lastId, err := result.LastInsertId()
	if err == nil {
		opt.Id = int64(lastId)
	}

	if AfterInsertPost != nil {
		AfterInsertPost(handler, opt)
	}
	return nil
}

// Update an entry
func (opt *Post) Update(handler *goje.Context) error {

	if handler == nil {
		handler = opt.ctx
	}

	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeUpdatePost != nil {
		err := BeforeUpdatePost(handler, opt)
		if err != nil {
			return err
		}
	}

	start := time.Now()
	// run query
	_, err := handler.DB.ExecContext(handler.Ctx, "UPDATE posts SET user_id=?,title=?,slug=?,body=?,rating=?,views=?,published_at=?,updated_at=? WHERE id=?", opt.UserId, opt.Title, opt.Slug, opt.Body, opt.Rating, opt.Views, opt.PublishedAt, opt.UpdatedAt, opt.Id)
	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=*Post.Update()\n", elapsed)
	}

	if err != nil {
		return err
	}

	if AfterUpdatePost != nil {
		AfterUpdatePost(handler, opt)
	}
	return nil

}

// GetPostById get one object of Post by primary keys
func GetPostById(handler *goje.Context, Id interface{}) (*Post, error) {

	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}
	start := time.Now()
	// run query
	row := handler.DB.QueryRowContext(handler.Ctx, "SELECT user_id,title,slug,body,rating,views,published_at,updated_at,id FROM posts WHERE id=?", Id)
	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetPostById()\n", elapsed)
	}

	if row.Err() != nil {
		return nil, row.Err()
	}

	var out Post
	out.ctx = handler
	err := row.Scan(&out.UserId, &out.Title, &out.Slug, &out.Body, &out.Rating, &out.Views, &out.PublishedAt, &out.UpdatedAt, &out.Id)
	return &out, err
}

// Get data attention by uq_posts_slug index
func GetPostBySlug(handler *goje.Context, SlugArg interface{}) (*Post, error) {
	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}

	start := time.Now()
	// run query
	row := handler.DB.QueryRowContext(handler.Ctx, "SELECT user_id,title,slug,body,rating,views,published_at,updated_at,id FROM posts WHERE slug=?", SlugArg)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetPostBySlug\n", elapsed)
	}

	if row.Err() != nil {
		return nil, row.Err()
	}

	var out Post
	out.ctx = handler

	err := row.Scan(&out.UserId, &out.Title, &out.Slug, &out.Body, &out.Rating, &out.Views, &out.PublishedAt, &out.UpdatedAt, &out.Id)
	return &out, err
}

// GetPosts Get list of entities by query
func GetPosts(handler *goje.Context, Queries ...goje.QueryInterface) ([]Post, error) {
	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}

	query, args, err := goje.SelectQueryBuilder("posts", PostColumnsWithTable, Queries)
	if err != nil {
		return nil, err
	}
	start := time.Now()

	rows, err := handler.DB.QueryContext(handler.Ctx, query, args...)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetPosts\n", elapsed)
	}

	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var out []Post
	for rows.Next() {
		var c Post
		c.ctx = handler
		err = rows.Scan(&c.UserId, &c.Title, &c.Slug, &c.Body, &c.Rating, &c.Views, &c.PublishedAt, &c.UpdatedAt, &c.Id)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, nil
}

// CountPosts count list of entities
func CountPosts(handler *goje.Context, Queries ...goje.QueryInterface) (int, error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}

	query, args, err := goje.SelectQueryBuilder("posts", []string{"COUNT(*) AS total"}, Queries)
	if err != nil {
		return -1, err
	}

	row := handler.DB.QueryRowContext(handler.Ctx, query, args...)

	if row.Err() != nil {
		return -1, row.Err()
	}

	var total int
	err = row.Scan(&total)

	return total, err
}

// Load User child by user_id
func (opt *Post) LoadUserIdUser() error {

	if opt.ctx == nil {
		return goje.ErrHandlerIsNil
	}

	if opt.parent != nil && opt.parent.GetTableName() == "users" {
		return goje.ErrRecursiveLoad
	}

	rows, err := GetUsers(opt.ctx, goje.Where("id = ?", opt.UserId))

	if err != nil {
		return err
	}

	if len(rows) > 0 {
		obj := rows[0]
		obj.parent = *opt
		opt.UserIdUser = &obj
	}

	return nil
}
