// Autogenerated by genigo(0.1.0)
// Please don't edit this file
// If you want add some helpers/triggers you should open a different file such as users.helper.go
package models

import (
	"log"
	"time"

	"database/sql"
	"github.com/shopspring/decimal"

	"github.com/genigo/goje"
)

type User struct {
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	Meta      interface{}     `db:"meta" json:"meta"`
	Balance   decimal.Decimal `db:"balance" json:"balance"`

	//Status: Enum acceptable values(active,pending,blocked)
	Status   UserStatus     `db:"status" json:"status"`
	IsActive int8           `db:"is_active" json:"is_active"`
	Nickname sql.NullString `db:"nickname" json:"nickname"`
	Email    string         `db:"email" json:"email"`
	Name     string         `db:"name" json:"name"`
	//Primary Key Auto Increment
	Id int64 `db:"id" json:"id"`

	//relation one to many Posts [user_id -> id]
	PostsByUserIdRel *[]Post `db:"-" json:"posts_by_user_id"`
	//internal context, db handler
	ctx    *goje.Context `db:"-" json:"-"`
	parent goje.Entity   `db:"-" json:"-"`
}

var BeforeInsertUser func(*goje.Context, *User) error
var BeforeUpdateUser func(*goje.Context, *User) error
var BeforeDeleteUser func(*goje.Context, *User) error
var AfterInsertUser func(*goje.Context, *User)
var AfterUpdateUser func(*goje.Context, *User)
var AfterDeleteUser func(*goje.Context, *User)

const UserTableName = "users"
const UserPrimaryKey = "id"

// List of Columns of table
var UserColumns = []string{
	"created_at", "meta", "balance", "status", "is_active", "nickname", "email", "name", "id",
}

// List of Columns merged with table name
var UserColumnsWithTable = []string{
	"users.created_at", "users.meta", "users.balance", "users.status", "users.is_active", "users.nickname", "users.email", "users.name", "users.id",
}

type UserStatus string

const (
	UserStatusActive  UserStatus = "active"
	UserStatusPending UserStatus = "pending"
	UserStatusBlocked UserStatus = "blocked"
)

// Tablename returns real table name in the database
// a helper method for goje.Entity interface
func (opt User) GetTableName() string {
	return UserTableName
}

// GetCtx returns current context handler
func (opt User) GetCtx() *goje.Context {
	return opt.ctx
}

// SetCtx set context handler for current object
func (opt *User) SetCtx(ctx *goje.Context) {
	opt.ctx = ctx
}

// GetParent returns parent object
func (opt User) GetParent() *goje.Entity {
	return &opt.parent
}

// Columns returns list of table columns
// a helper method for goje.Entity interface
func (opt User) GetColumns() []string {
	return UserColumns
}

// Delete multiple User by queries
// This method dosen't support After,Before Triggers ...
func DeleteUserRaw(handler *goje.Context, Queries ...goje.QueryInterface) (rowsAffected int64, err error) {
	return handler.RawDelete("users", Queries)
}

// Insert multiple User with INTO
// This method dosen't support After,Before Triggers ...
func BulkInsertUser(handler *goje.Context, entities []User) (rowsInserted int64, err error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}

	rows := make([]map[string]interface{}, len(entities))

	for i := 0; i < len(entities); i++ {
		rows[i] = make(map[string]interface{})
		rows[i]["meta"] = entities[i].Meta
		rows[i]["balance"] = entities[i].Balance
		rows[i]["status"] = entities[i].Status
		rows[i]["is_active"] = entities[i].IsActive
		rows[i]["nickname"] = entities[i].Nickname
		rows[i]["email"] = entities[i].Email
		rows[i]["name"] = entities[i].Name
		rows[i]["id"] = entities[i].Id
	}
	return handler.RawBulkInsert("users", rows)
}

// Update custom columns of User
// This method dosen't support After,Before Triggers ...
func UpdateUser(handler *goje.Context, Cols map[string]any, Queries ...goje.QueryInterface) (rowsAffected int64, err error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}
	return handler.RawUpdate("users", Cols, Queries...)
}

// Insert multiple User with IGNORE
// This method dosen't support After,Before Triggers ...
func BulkInsertIgnoreUser(handler *goje.Context, entities []User) (rowsInserted int64, err error) {
	rows := make([]map[string]interface{}, len(entities))

	for i := 0; i < len(entities); i++ {
		rows[i] = make(map[string]interface{})
		rows[i]["meta"] = entities[i].Meta
		rows[i]["balance"] = entities[i].Balance
		rows[i]["status"] = entities[i].Status
		rows[i]["is_active"] = entities[i].IsActive
		rows[i]["nickname"] = entities[i].Nickname
		rows[i]["email"] = entities[i].Email
		rows[i]["name"] = entities[i].Name
		rows[i]["id"] = entities[i].Id
	}
	return handler.RawBulkInsertIgnore("users", rows)
}

// Delete delete an entry
func (opt *User) Delete(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeDeleteUser != nil {
		err := BeforeDeleteUser(handler, opt)
		if err != nil {
			return err
		}
	}

	start := time.Now()
	// run query
	_, err := handler.DB.ExecContext(handler.Ctx, `DELETE FROM users WHERE id=?`, opt.Id)

	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=User.Delete()\n", elapsed)
	}

	if err != nil {
		return err
	}

	if AfterDeleteUser != nil {
		AfterDeleteUser(handler, opt)
	}

	return nil

}

// Save update an entry when primary key is set or create an entry when primary key isn't set
func (opt *User) Save(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if opt.Id == 0 {
		return opt.Insert(handler)
	}

	return opt.Update(handler)

}

// Insert create an entry
func (opt *User) Insert(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeInsertUser != nil {
		err := BeforeInsertUser(handler, opt)
		if err != nil {
			return err
		}
	}

	if opt.CreatedAt.IsZero() {
		opt.CreatedAt = time.Now()
	}

	start := time.Now()

	result, err := handler.DB.ExecContext(handler.Ctx, `INSERT INTO users(created_at,meta,balance,status,is_active,nickname,email,name) VALUES(?,?,?,?,?,?,?,?)`, opt.CreatedAt, opt.Meta, opt.Balance, opt.Status, opt.IsActive, opt.Nickname, opt.Email, opt.Name)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=*User.Insert()\n", elapsed)
	}

	if err != nil {
		return err
	}

	lastId, err := result.LastInsertId()
	if err == nil {
		opt.Id = int64(lastId)
	}

	if AfterInsertUser != nil {
		AfterInsertUser(handler, opt)
	}
	return nil
}

// Update an entry
func (opt *User) Update(handler *goje.Context) error {

	if handler == nil {
		handler = opt.ctx
	}

	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeUpdateUser != nil {
		err := BeforeUpdateUser(handler, opt)
		if err != nil {
			return err
		}
	}

	start := time.Now()
	// run query
	_, err := handler.DB.ExecContext(handler.Ctx, "UPDATE users SET created_at=?,meta=?,balance=?,status=?,is_active=?,nickname=?,email=?,name=? WHERE id=?", opt.CreatedAt, opt.Meta, opt.Balance, opt.Status, opt.IsActive, opt.Nickname, opt.Email, opt.Name, opt.Id)
	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=*User.Update()\n", elapsed)
	}

	if err != nil {
		return err
	}

	if AfterUpdateUser != nil {
		AfterUpdateUser(handler, opt)
	}
	return nil

}

// GetUserById get one object of User by primary keys
func GetUserById(handler *goje.Context, Id interface{}) (*User, error) {

	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}
	start := time.Now()
	// run query
	row := handler.DB.QueryRowContext(handler.Ctx, "SELECT created_at,meta,balance,status,is_active,nickname,email,name,id FROM users WHERE id=?", Id)
	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetUserById()\n", elapsed)
	}

	if row.Err() != nil {
		return nil, row.Err()
	}

	var out User
	out.ctx = handler
	err := row.Scan(&out.CreatedAt, &out.Meta, &out.Balance, &out.Status, &out.IsActive, &out.Nickname, &out.Email, &out.Name, &out.Id)
	return &out, err
}

// Get data attention by uq_users_email index
func GetUserByEmail(handler *goje.Context, EmailArg interface{}) (*User, error) {
	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}

	start := time.Now()
	// run query
	row := handler.DB.QueryRowContext(handler.Ctx, "SELECT created_at,meta,balance,status,is_active,nickname,email,name,id FROM users WHERE email=?", EmailArg)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetUserByEmail\n", elapsed)
	}

	if row.Err() != nil {
		return nil, row.Err()
	}

	var out User
	out.ctx = handler

	err := row.Scan(&out.CreatedAt, &out.Meta, &out.Balance, &out.Status, &out.IsActive, &out.Nickname, &out.Email, &out.Name, &out.Id)
	return &out, err
}

// GetUsers Get list of entities by query
func GetUsers(handler *goje.Context, Queries ...goje.QueryInterface) ([]User, error) {
	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}

	query, args, err := goje.SelectQueryBuilder("users", UserColumnsWithTable, Queries)
	if err != nil {
		return nil, err
	}
	start := time.Now()

	rows, err := handler.DB.QueryContext(handler.Ctx, query, args...)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetUsers\n", elapsed)
	}

	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var out []User
	for rows.Next() {
		var c User
		c.ctx = handler
		err = rows.Scan(&c.CreatedAt, &c.Meta, &c.Balance, &c.Status, &c.IsActive, &c.Nickname, &c.Email, &c.Name, &c.Id)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, nil
}

// CountUsers count list of entities
func CountUsers(handler *goje.Context, Queries ...goje.QueryInterface) (int, error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}

	query, args, err := goje.SelectQueryBuilder("users", []string{"COUNT(*) AS total"}, Queries)
	if err != nil {
		return -1, err
	}

	row := handler.DB.QueryRowContext(handler.Ctx, query, args...)

	if row.Err() != nil {
		return -1, row.Err()
	}

	var total int
	err = row.Scan(&total)

	return total, err
}

// Load Posts by user_id
func (opt *User) LoadPostsByUserId(Queries ...goje.QueryInterface) error {

	if opt.ctx == nil {
		return goje.ErrHandlerIsNil
	}

	if opt.parent != nil && opt.parent.GetTableName() == "posts" {
		return goje.ErrRecursiveLoad
	}
	Queries = append(Queries, goje.Where("user_id = ?", opt.Id))

	rows, err := GetPosts(opt.ctx, Queries...)

	if err != nil {
		return err
	}

	rowsWithParent := make([]Post, len(rows))
	for i := 0; i < len(rows); i++ {
		obj := rows[i]
		obj.parent = *opt
		rowsWithParent[i] = obj
	}

	opt.PostsByUserIdRel = &rowsWithParent

	return nil
}
