// Package integration compiles the models generated by genigo for both
// drivers and exercises the full CRUD surface against live databases
// (docker-compose.yml at the repository root).
//
// Env: TEST_MYSQL_DSN, TEST_POSTGRES_DSN  (subtests skip when unset)
//
//	mysql:    root:genigo@tcp(127.0.0.1:3307)/genigo_test
//	postgres: postgres://genigo:genigo@127.0.0.1:5433/genigo_test?sslmode=disable
package integration

import (
	"context"
	"database/sql"
	"net/url"
	"os"
	"testing"
	"time"

	"github.com/genigo/goje"
	"github.com/go-sql-driver/mysql"
	"github.com/shopspring/decimal"

	mymodels "github.com/genigo/genigo/integration/models-mysql/models"
	pgmodels "github.com/genigo/genigo/integration/models-postgres/models"
)

func sqlNullString(s string) sql.NullString {
	return sql.NullString{String: s, Valid: true}
}

func truncate(t *testing.T, handler *goje.Context, driver string) {
	t.Helper()
	quote := func(s string) string {
		if driver == "postgres" {
			return `"` + s + `"`
		}
		return s
	}
	for _, table := range []string{"posts", "users"} {
		if _, err := handler.DB.ExecContext(handler.Ctx, "DELETE FROM "+quote(table)); err != nil {
			t.Fatalf("truncate %s: %+v", table, err)
		}
	}
}

func mysqlConf(t *testing.T) *goje.DBConfig {
	t.Helper()
	dsn := os.Getenv("TEST_MYSQL_DSN")
	if dsn == "" {
		t.Skip("TEST_MYSQL_DSN is not set")
	}
	cfg, err := mysql.ParseDSN(dsn)
	if err != nil {
		t.Fatal(err)
	}
	host, port := "127.0.0.1", "3306"
	for i := len(cfg.Addr) - 1; i >= 0; i-- {
		if cfg.Addr[i] == ':' {
			host, port = cfg.Addr[:i], cfg.Addr[i+1:]
			break
		}
	}
	return &goje.DBConfig{
		Driver: "mysql", User: cfg.User, Password: cfg.Passwd,
		Host: host, Port: atoi(port), Schema: cfg.DBName,
	}
}

func pgConf(t *testing.T) *goje.DBConfig {
	t.Helper()
	dsn := os.Getenv("TEST_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("TEST_POSTGRES_DSN is not set")
	}
	u, err := url.Parse(dsn)
	if err != nil {
		t.Fatal(err)
	}
	conf := &goje.DBConfig{
		Driver: "postgres", Host: u.Hostname(), Port: 5432,
		Schema: u.Path, Flags: map[string]string{"sslmode": "disable"},
	}
	if p := u.Port(); p != "" {
		conf.Port = atoi(p)
	}
	if len(conf.Schema) > 0 && conf.Schema[0] == '/' {
		conf.Schema = conf.Schema[1:]
	}
	if u.User != nil {
		conf.User = u.User.Username()
		conf.Password, _ = u.User.Password()
	}
	return conf
}

func atoi(s string) int {
	n := 0
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return n
		}
		n = n*10 + int(s[i]-'0')
	}
	return n
}

func mustOK(t *testing.T, err error, msg string) {
	t.Helper()
	if err != nil {
		t.Fatalf("%s: %+v", msg, err)
	}
}

// ---- mysql ----

func TestMySQLCRUD(t *testing.T) {
	conf := mysqlConf(t)
	mustOK(t, goje.InitDB(conf), "connect")
	handler := goje.MakeHandler(context.Background())
	truncate(t, handler, "mysql")

	u := &mymodels.User{
		Name: "Mahmoud", Email: "mahmoud@example.com",
		Nickname: sqlNullString("Mahi"), IsActive: 1,
		Status:  mymodels.UserStatusActive,
		Balance: decimal.NewFromFloat(10.5),
	}
	mustOK(t, u.Insert(handler), "insert")
	if u.Id == 0 {
		t.Fatal("LastInsertId did not come back")
	}

	got, err := mymodels.GetUserById(handler, u.Id)
	mustOK(t, err, "get by id")
	if got.Name != u.Name || got.Email != u.Email || !got.Balance.Equal(u.Balance) {
		t.Fatalf("round-trip mismatch: %+v", got)
	}
	if !got.Nickname.Valid || got.Nickname.String != "Mahi" {
		t.Fatalf("nullable string mismatch: %+v", got.Nickname)
	}
	if got.Status != mymodels.UserStatusActive {
		t.Fatalf("enum mismatch: %v", got.Status)
	}

	got.Name = "Updated"
	mustOK(t, got.Save(handler), "save/update")

	byEmail, err := mymodels.GetUserByEmail(handler, "mahmoud@example.com")
	mustOK(t, err, "get by unique index")
	if byEmail.Name != "Updated" {
		t.Fatalf("update did not persist: %s", byEmail.Name)
	}

	p := &mymodels.Post{
		UserId: got.Id, Title: "Hello", Slug: "hello",
		Rating: decimal.NewFromFloat(4.5), Views: 10,
	}
	mustOK(t, p.Insert(handler), "post insert")

	mustOK(t, got.LoadPostsByUserId(), "relation load")
	if got.PostsByUserIdRel == nil || len(*got.PostsByUserIdRel) != 1 {
		t.Fatalf("relation load returned %+v", got.PostsByUserIdRel)
	}

	list, err := mymodels.GetUsers(handler,
		goje.Where("name = ?", "Updated"),
		goje.Order("id"),
		goje.Limit(5),
	)
	mustOK(t, err, "GetUsers")
	if len(list) != 1 {
		t.Fatalf("GetUsers returned %d rows", len(list))
	}

	count, err := mymodels.CountUsers(handler)
	mustOK(t, err, "CountUsers")
	if count != 1 {
		t.Fatalf("count = %d, want 1", count)
	}

	inserted, err := mymodels.BulkInsertUser(handler, []mymodels.User{
		{Name: "A", Email: "a@example.com", Status: mymodels.UserStatusPending},
		{Name: "B", Email: "b@example.com", Status: mymodels.UserStatusPending},
	})
	mustOK(t, err, "BulkInsert")
	if inserted != 2 {
		t.Fatalf("bulk inserted %d, want 2", inserted)
	}

	// duplicate email is skipped by INSERT IGNORE
	inserted, err = mymodels.BulkInsertIgnoreUser(handler, []mymodels.User{
		{Name: "A2", Email: "a@example.com", Status: mymodels.UserStatusPending},
		{Name: "C", Email: "c@example.com", Status: mymodels.UserStatusPending},
	})
	mustOK(t, err, "BulkInsertIgnore")
	if inserted != 1 {
		t.Fatalf("ignore-insert inserted %d, want 1", inserted)
	}

	affected, err := mymodels.UpdateUser(handler,
		map[string]any{"name": "Renamed"},
		goje.Where("email = ?", "b@example.com"),
	)
	mustOK(t, err, "UpdateUser")
	if affected != 1 {
		t.Fatalf("raw update affected %d, want 1", affected)
	}

	// transactions: commit
	tx, err := goje.MakeTxHandler(context.Background(), nil)
	mustOK(t, err, "begin tx")
	txUser := &mymodels.User{Name: "Tx", Email: "tx@example.com", Status: mymodels.UserStatusActive}
	mustOK(t, txUser.Insert(tx), "insert in tx")
	mustOK(t, tx.Commit(), "commit")

	// transactions: rollback
	tx, err = goje.MakeTxHandler(context.Background(), nil)
	mustOK(t, err, "begin tx")
	txUser = &mymodels.User{Name: "Gone", Email: "gone@example.com", Status: mymodels.UserStatusActive}
	mustOK(t, txUser.Insert(tx), "insert in tx")
	mustOK(t, tx.Rollback(), "rollback")

	count, err = mymodels.CountUsers(handler, goje.Where("email = ?", "gone@example.com"))
	mustOK(t, err, "count after rollback")
	if count != 0 {
		t.Fatal("rolled back row is visible")
	}

	affected, err = mymodels.DeleteUserRaw(handler, goje.Where("email = ?", "tx@example.com"))
	mustOK(t, err, "DeleteUserRaw")
	if affected != 1 {
		t.Fatalf("delete affected %d, want 1", affected)
	}
}

// ---- postgres ----

func TestPostgresCRUD(t *testing.T) {
	conf := pgConf(t)
	mustOK(t, goje.InitDB(conf), "connect")
	handler := goje.MakeHandler(context.Background())
	truncate(t, handler, "postgres")

	u := &pgmodels.User{
		Name: "Mahmoud", Email: "mahmoud@example.com",
		Nickname: sqlNullString("Mahi"), IsActive: true,
		Status:  pgmodels.UserStatusActive,
		Balance: decimal.NewFromFloat(10.5),
		Tags:    goje.StringArray{"go", "sql"},
	}
	mustOK(t, u.Insert(handler), "insert")

	// RETURNING brings back the identity key, the uuid default and now()
	if u.Id == 0 {
		t.Fatal("RETURNING id did not come back")
	}
	if !u.CreatedAt.After(time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)) {
		t.Fatalf("RETURNING created_at not scanned: %+v", u.CreatedAt)
	}
	if !u.Ref.Valid || len(u.Ref.String) != 36 {
		t.Fatalf("RETURNING uuid default not scanned: %+v", u.Ref)
	}

	got, err := pgmodels.GetUserById(handler, u.Id)
	mustOK(t, err, "get by id")
	if got.Name != u.Name || !got.Balance.Equal(u.Balance) {
		t.Fatalf("round-trip mismatch: %+v", got)
	}
	if len(got.Tags) != 2 || got.Tags[0] != "go" || got.Tags[1] != "sql" {
		t.Fatalf("array round-trip mismatch: %+v", got.Tags)
	}

	got.Name = "Updated"
	mustOK(t, got.Save(handler), "save/update")

	byEmail, err := pgmodels.GetUserByEmail(handler, "mahmoud@example.com")
	mustOK(t, err, "get by unique index")
	if byEmail.Name != "Updated" {
		t.Fatalf("update did not persist: %s", byEmail.Name)
	}

	p := &pgmodels.Post{
		UserId: got.Id, Title: "Hello", Slug: "hello",
		Rating: decimal.NewFromFloat(4.5), Views: 10,
	}
	mustOK(t, p.Insert(handler), "post insert")

	mustOK(t, got.LoadPostsByUserId(), "relation load")
	if got.PostsByUserIdRel == nil || len(*got.PostsByUserIdRel) != 1 {
		t.Fatalf("relation load returned %+v", got.PostsByUserIdRel)
	}

	list, err := pgmodels.GetUsers(handler,
		goje.Where("name = ?", "Updated"),
		goje.Order("id"),
		goje.Limit(5),
	)
	mustOK(t, err, "GetUsers")
	if len(list) != 1 {
		t.Fatalf("GetUsers returned %d rows", len(list))
	}

	count, err := pgmodels.CountUsers(handler)
	mustOK(t, err, "CountUsers")
	if count != 1 {
		t.Fatalf("count = %d, want 1", count)
	}

	inserted, err := pgmodels.BulkInsertUser(handler, []pgmodels.User{
		{Name: "A", Email: "a@example.com", Status: pgmodels.UserStatusPending},
		{Name: "B", Email: "b@example.com", Status: pgmodels.UserStatusPending},
	})
	mustOK(t, err, "BulkInsert")
	if inserted != 2 {
		t.Fatalf("bulk inserted %d, want 2", inserted)
	}

	// duplicate email is skipped by ON CONFLICT DO NOTHING
	inserted, err = pgmodels.BulkInsertIgnoreUser(handler, []pgmodels.User{
		{Name: "A2", Email: "a@example.com", Status: pgmodels.UserStatusPending},
		{Name: "C", Email: "c@example.com", Status: pgmodels.UserStatusPending},
	})
	mustOK(t, err, "BulkInsertIgnore")
	if inserted != 1 {
		t.Fatalf("conflict-insert inserted %d, want 1", inserted)
	}

	affected, err := pgmodels.UpdateUser(handler,
		map[string]any{"name": "Renamed"},
		goje.Where("email = ?", "b@example.com"),
	)
	mustOK(t, err, "UpdateUser")
	if affected != 1 {
		t.Fatalf("raw update affected %d, want 1", affected)
	}

	tx, err := goje.MakeTxHandler(context.Background(), nil)
	mustOK(t, err, "begin tx")
	txUser := &pgmodels.User{Name: "Tx", Email: "tx@example.com", Status: pgmodels.UserStatusActive}
	mustOK(t, txUser.Insert(tx), "insert in tx")
	mustOK(t, tx.Commit(), "commit")

	tx, err = goje.MakeTxHandler(context.Background(), nil)
	mustOK(t, err, "begin tx")
	txUser = &pgmodels.User{Name: "Gone", Email: "gone@example.com", Status: pgmodels.UserStatusActive}
	mustOK(t, txUser.Insert(tx), "insert in tx")
	mustOK(t, tx.Rollback(), "rollback")

	count, err = pgmodels.CountUsers(handler, goje.Where("email = ?", "gone@example.com"))
	mustOK(t, err, "count after rollback")
	if count != 0 {
		t.Fatal("rolled back row is visible")
	}

	affected, err = pgmodels.DeleteUserRaw(handler, goje.Where("email = ?", "tx@example.com"))
	mustOK(t, err, "DeleteUserRaw")
	if affected != 1 {
		t.Fatalf("delete affected %d, want 1", affected)
	}
}
