// Autogenerated by genigo(0.1.0)
// Please don't edit this file
// If you want add some helpers/triggers you should open a different file such as users.helper.go
package models

import (
	"log"
	"time"

	"database/sql"
	"github.com/shopspring/decimal"

	"github.com/genigo/goje"
)

type User struct {

	//Primary Key Auto Increment
	Id       int64          `db:"id" json:"id"`
	Name     string         `db:"name" json:"name"`
	Email    string         `db:"email" json:"email"`
	Nickname sql.NullString `db:"nickname" json:"nickname"`
	IsActive bool           `db:"is_active" json:"is_active"`

	//Status: Enum acceptable values(active,pending,blocked)
	Status    UserStatus       `db:"status" json:"status"`
	Balance   decimal.Decimal  `db:"balance" json:"balance"`
	Meta      interface{}      `db:"meta" json:"meta"`
	Tags      goje.StringArray `db:"tags" json:"tags"`
	Ref       sql.NullString   `db:"ref" json:"ref"`
	CreatedAt time.Time        `db:"created_at" json:"created_at"`

	//relation one to many Posts [user_id -> id]
	PostsByUserIdRel *[]Post `db:"-" json:"posts_by_user_id"`
	//internal context, db handler
	ctx    *goje.Context `db:"-" json:"-"`
	parent goje.Entity   `db:"-" json:"-"`
}

var BeforeInsertUser func(*goje.Context, *User) error
var BeforeUpdateUser func(*goje.Context, *User) error
var BeforeDeleteUser func(*goje.Context, *User) error
var AfterInsertUser func(*goje.Context, *User)
var AfterUpdateUser func(*goje.Context, *User)
var AfterDeleteUser func(*goje.Context, *User)

const UserTableName = "users"
const UserPrimaryKey = "id"

// List of Columns of table
var UserColumns = []string{
	"id", "name", "email", "nickname", "is_active", "status", "balance", "meta", "tags", "ref", "created_at",
}

// List of Columns merged with table name
var UserColumnsWithTable = []string{
	"users.id", "users.name", "users.email", "users.nickname", "users.is_active", "users.status", "users.balance", "users.meta", "users.tags", "users.ref", "users.created_at",
}

type UserStatus string

const (
	UserStatusActive  UserStatus = "active"
	UserStatusPending UserStatus = "pending"
	UserStatusBlocked UserStatus = "blocked"
)

// Tablename returns real table name in the database
// a helper method for goje.Entity interface
func (opt User) GetTableName() string {
	return UserTableName
}

// GetCtx returns current context handler
func (opt User) GetCtx() *goje.Context {
	return opt.ctx
}

// SetCtx set context handler for current object
func (opt *User) SetCtx(ctx *goje.Context) {
	opt.ctx = ctx
}

// GetParent returns parent object
func (opt User) GetParent() *goje.Entity {
	return &opt.parent
}

// Columns returns list of table columns
// a helper method for goje.Entity interface
func (opt User) GetColumns() []string {
	return UserColumns
}

// Delete multiple User by queries
// This method dosen't support After,Before Triggers ...
func DeleteUserRaw(handler *goje.Context, Queries ...goje.QueryInterface) (rowsAffected int64, err error) {
	return handler.RawDelete("users", Queries)
}

// Insert multiple User with INTO
// This method dosen't support After,Before Triggers ...
func BulkInsertUser(handler *goje.Context, entities []User) (rowsInserted int64, err error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}

	rows := make([]map[string]interface{}, len(entities))

	for i := 0; i < len(entities); i++ {
		rows[i] = make(map[string]interface{})
		rows[i]["name"] = entities[i].Name
		rows[i]["email"] = entities[i].Email
		rows[i]["nickname"] = entities[i].Nickname
		rows[i]["is_active"] = entities[i].IsActive
		rows[i]["status"] = entities[i].Status
		rows[i]["balance"] = entities[i].Balance
		rows[i]["meta"] = entities[i].Meta
		rows[i]["tags"] = entities[i].Tags
	}
	return handler.RawBulkInsert("users", rows)
}

// Update custom columns of User
// This method dosen't support After,Before Triggers ...
func UpdateUser(handler *goje.Context, Cols map[string]any, Queries ...goje.QueryInterface) (rowsAffected int64, err error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}
	return handler.RawUpdate("users", Cols, Queries...)
}

// Insert multiple User with IGNORE
// This method dosen't support After,Before Triggers ...
func BulkInsertIgnoreUser(handler *goje.Context, entities []User) (rowsInserted int64, err error) {
	rows := make([]map[string]interface{}, len(entities))

	for i := 0; i < len(entities); i++ {
		rows[i] = make(map[string]interface{})
		rows[i]["name"] = entities[i].Name
		rows[i]["email"] = entities[i].Email
		rows[i]["nickname"] = entities[i].Nickname
		rows[i]["is_active"] = entities[i].IsActive
		rows[i]["status"] = entities[i].Status
		rows[i]["balance"] = entities[i].Balance
		rows[i]["meta"] = entities[i].Meta
		rows[i]["tags"] = entities[i].Tags
	}
	return handler.RawBulkInsertIgnore("users", rows)
}

// Delete delete an entry
func (opt *User) Delete(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeDeleteUser != nil {
		err := BeforeDeleteUser(handler, opt)
		if err != nil {
			return err
		}
	}

	start := time.Now()
	// run query
	_, err := handler.DB.ExecContext(handler.Ctx, `DELETE FROM "users" WHERE "id" = $1`, opt.Id)

	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=User.Delete()\n", elapsed)
	}

	if err != nil {
		return err
	}

	if AfterDeleteUser != nil {
		AfterDeleteUser(handler, opt)
	}

	return nil

}

// Save update an entry when primary key is set or create an entry when primary key isn't set
func (opt *User) Save(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if opt.Id == 0 {
		return opt.Insert(handler)
	}

	return opt.Update(handler)

}

// Insert create an entry
func (opt *User) Insert(handler *goje.Context) error {
	if handler == nil {
		handler = opt.ctx
	}
	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeInsertUser != nil {
		err := BeforeInsertUser(handler, opt)
		if err != nil {
			return err
		}
	}

	start := time.Now()

	row := handler.DB.QueryRowContext(handler.Ctx, `INSERT INTO "users"("name","email","nickname","is_active","status","balance","meta","tags") VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id","ref","created_at"`, opt.Name, opt.Email, opt.Nickname, opt.IsActive, opt.Status, opt.Balance, opt.Meta, opt.Tags)
	err := row.Scan(&opt.Id, &opt.Ref, &opt.CreatedAt)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=*User.Insert()\n", elapsed)
	}

	if err != nil {
		return err
	}

	if AfterInsertUser != nil {
		AfterInsertUser(handler, opt)
	}
	return nil
}

// Update an entry
func (opt *User) Update(handler *goje.Context) error {

	if handler == nil {
		handler = opt.ctx
	}

	if handler == nil {
		return goje.ErrHandlerIsNil
	}

	if BeforeUpdateUser != nil {
		err := BeforeUpdateUser(handler, opt)
		if err != nil {
			return err
		}
	}

	start := time.Now()
	// run query
	_, err := handler.DB.ExecContext(handler.Ctx, `UPDATE "users" SET "name" = $1,"email" = $2,"nickname" = $3,"is_active" = $4,"status" = $5,"balance" = $6,"meta" = $7,"tags" = $8,"ref" = $9,"created_at" = $10 WHERE "id" = $11`, opt.Name, opt.Email, opt.Nickname, opt.IsActive, opt.Status, opt.Balance, opt.Meta, opt.Tags, opt.Ref, opt.CreatedAt, opt.Id)
	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=*User.Update()\n", elapsed)
	}

	if err != nil {
		return err
	}

	if AfterUpdateUser != nil {
		AfterUpdateUser(handler, opt)
	}
	return nil

}

// GetUserById get one object of User by primary keys
func GetUserById(handler *goje.Context, Id interface{}) (*User, error) {

	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}
	start := time.Now()
	// run query
	row := handler.DB.QueryRowContext(handler.Ctx, `SELECT "id","name","email","nickname","is_active","status","balance","meta","tags","ref","created_at" FROM "users" WHERE "id" = $1`, Id)
	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetUserById()\n", elapsed)
	}

	if row.Err() != nil {
		return nil, row.Err()
	}

	var out User
	out.ctx = handler
	err := row.Scan(&out.Id, &out.Name, &out.Email, &out.Nickname, &out.IsActive, &out.Status, &out.Balance, &out.Meta, &out.Tags, &out.Ref, &out.CreatedAt)
	return &out, err
}

// Get data attention by uq_users_email index
func GetUserByEmail(handler *goje.Context, EmailArg interface{}) (*User, error) {
	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}

	start := time.Now()
	// run query
	row := handler.DB.QueryRowContext(handler.Ctx, `SELECT "id","name","email","nickname","is_active","status","balance","meta","tags","ref","created_at" FROM "users" WHERE "email" = $1`, EmailArg)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetUserByEmail\n", elapsed)
	}

	if row.Err() != nil {
		return nil, row.Err()
	}

	var out User
	out.ctx = handler

	err := row.Scan(&out.Id, &out.Name, &out.Email, &out.Nickname, &out.IsActive, &out.Status, &out.Balance, &out.Meta, &out.Tags, &out.Ref, &out.CreatedAt)
	return &out, err
}

// GetUsers Get list of entities by query
func GetUsers(handler *goje.Context, Queries ...goje.QueryInterface) ([]User, error) {
	if handler == nil {
		return nil, goje.ErrHandlerIsNil
	}

	query, args, err := goje.SelectQueryBuilder("users", UserColumnsWithTable, Queries)
	if err != nil {
		return nil, err
	}
	start := time.Now()

	rows, err := handler.DB.QueryContext(handler.Ctx, query, args...)

	// log slow queries
	elapsed := time.Since(start)
	if goje.SlowQueryLogTimeout > 0 && elapsed > goje.SlowQueryLogTimeout {
		log.Printf("[SLOW QUERY] took=%s method=GetUsers\n", elapsed)
	}

	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var out []User
	for rows.Next() {
		var c User
		c.ctx = handler
		err = rows.Scan(&c.Id, &c.Name, &c.Email, &c.Nickname, &c.IsActive, &c.Status, &c.Balance, &c.Meta, &c.Tags, &c.Ref, &c.CreatedAt)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, nil
}

// CountUsers count list of entities
func CountUsers(handler *goje.Context, Queries ...goje.QueryInterface) (int, error) {
	if handler == nil {
		return -1, goje.ErrHandlerIsNil
	}

	query, args, err := goje.SelectQueryBuilder("users", []string{"COUNT(*) AS total"}, Queries)
	if err != nil {
		return -1, err
	}

	row := handler.DB.QueryRowContext(handler.Ctx, query, args...)

	if row.Err() != nil {
		return -1, row.Err()
	}

	var total int
	err = row.Scan(&total)

	return total, err
}

// Load Posts by user_id
func (opt *User) LoadPostsByUserId(Queries ...goje.QueryInterface) error {

	if opt.ctx == nil {
		return goje.ErrHandlerIsNil
	}

	if opt.parent != nil && opt.parent.GetTableName() == "posts" {
		return goje.ErrRecursiveLoad
	}
	Queries = append(Queries, goje.Where("user_id = ?", opt.Id))

	rows, err := GetPosts(opt.ctx, Queries...)

	if err != nil {
		return err
	}

	rowsWithParent := make([]Post, len(rows))
	for i := 0; i < len(rows); i++ {
		obj := rows[i]
		obj.parent = *opt
		rowsWithParent[i] = obj
	}

	opt.PostsByUserIdRel = &rowsWithParent

	return nil
}
