-- genigo test fixture: exercises every type/introspection feature on postgres.
-- Mirrors testdata/mysql.sql; users.id uses a serial (nextval default) and
-- posts.id uses an identity column so both AI detection paths are covered.
-- tags TEXT[] and ref UUID are postgres-native extras without a mysql counterpart.
CREATE TYPE user_status AS ENUM ('active', 'pending', 'blocked');

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  nickname VARCHAR(120) NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  status user_status NOT NULL DEFAULT 'active',
  balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  meta JSONB NULL,
  tags TEXT[] NULL,
  ref UUID NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id),
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(220) NOT NULL,
  body TEXT NULL,
  rating NUMERIC(4,2) NOT NULL DEFAULT 0,
  views INTEGER NOT NULL DEFAULT 0,
  published_at TIMESTAMPTZ NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_posts_slug UNIQUE (slug)
);
